<?php 

$_PROFILE_MODULES = array (
  0 => 
  array (
    'id' => '1',
    'module_name' => 'system',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/system.git',
    'private_clone_url' => 'git@github.com:diversen/system.git',
  ),
  1 => 
  array (
    'id' => '2',
    'module_name' => 'settings',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/settings.git',
    'private_clone_url' => 'git@github.com:diversen/settings.git',
  ),
  2 => 
  array (
    'id' => '3',
    'module_name' => 'error',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/error.git',
    'private_clone_url' => 'git@github.com:diversen/error.git',
  ),
  3 => 
  array (
    'id' => '4',
    'module_name' => 'content',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/content.git',
    'private_clone_url' => 'git@github.com:diversen/content.git',
  ),
  4 => 
  array (
    'id' => '5',
    'module_name' => 'files',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/files.git',
    'private_clone_url' => 'git@github.com:diversen/files.git',
  ),
  5 => 
  array (
    'id' => '6',
    'module_name' => 'account',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account.git',
    'private_clone_url' => 'git@github.com:diversen/account.git',
  ),
  6 => 
  array (
    'id' => '7',
    'module_name' => 'google_analytics',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0,5',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/google_analytics.git',
    'private_clone_url' => 'git@github.com:diversen/google_analytics.git',
  ),
  7 => 
  array (
    'id' => '8',
    'module_name' => 'gallery',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/gallery.git',
    'private_clone_url' => 'git@github.com:diversen/gallery.git',
  ),
  8 => 
  array (
    'id' => '9',
    'module_name' => 'account_profile',
    'module_version' => '1.71',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account_profile.git',
    'private_clone_url' => 'git@github.com:diversen/account_profile.git',
  ),

  12 => 
  array (
    'id' => '13',
    'module_name' => 'image',
    'module_version' => '1.711',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/image.git',
    'private_clone_url' => 'git@github.com:diversen/image.git',
  ),
  13 => 
  array (
    'id' => '14',
    'module_name' => 'addthis',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/addthis.git',
    'private_clone_url' => 'git@github.com:diversen/addthis.git',
  ),
  14 => 
  array (
    'id' => '15',
    'module_name' => 'comment',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/comment.git',
    'private_clone_url' => 'git@github.com:diversen/comment.git',
  ),

  16 => 
  array (
    'id' => '17',
    'module_name' => 'blog',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => '1',
    'public_clone_url' => 'git://github.com/diversen/blog.git',
    'private_clone_url' => 'git@github.com:diversen/blog.git',
  ),
  17 => 
  array (
    'id' => '18',
    'module_name' => 'tags',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/tags.git',
    'private_clone_url' => 'git@github.com:diversen/tags.git',
  ),
  18 => 
  array (
    'id' => '19',
    'module_name' => 'rss',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/rss.git',
    'private_clone_url' => 'git@github.com:diversen/rss.git',
  ),
  19 => 
  array (
    'id' => '20',
    'module_name' => 'remote',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => '1',
    'public_clone_url' => 'git://github.com/diversen/remote.git',
    'private_clone_url' => 'git@github.com:diversen/remote.git',
  ),
  20 => 
  array (
    'id' => '21',
    'module_name' => 'configdb',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '2',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/configdb.git',
    'private_clone_url' => 'git@github.com:diversen/configdb.git',
  ),
  21 => 
  array (
    'id' => '22',
    'module_name' => 'locales',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/locales.git',
    'private_clone_url' => 'git@github.com:diversen/locales.git',
  ),
  22 => 
  array (
    'id' => '23',
    'module_name' => 'menus',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/menus.git',
    'private_clone_url' => 'git@github.com:diversen/menus.git',
  ),
  23 => 
  array (
    'id' => '24',
    'module_name' => 'jquerysort',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/jquerysort.git',
    'private_clone_url' => 'git@github.com:diversen/jquerysort.git',
  ),
  24 => 
  array (
    'id' => '25',
    'module_name' => 'vote',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/vote.git',
    'private_clone_url' => 'git@github.com:diversen/vote.git',
  ),
  25 => 
  array (
    'id' => '26',
    'module_name' => 'image_captcha',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/image_captcha.git',
    'private_clone_url' => 'git@github.com:diversen/image_captcha.git',
  ),
  26 => 
  array (
    'id' => '27',
    'module_name' => 'flood',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/flood.git',
    'private_clone_url' => 'git@github.com:diversen/flood.git',
  ),
  27 => 
  array (
    'id' => '28',
    'module_name' => 'video',
    'module_version' => '1.70',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/video.git',
    'private_clone_url' => 'git@github.com:diversen/video.git',
  ),
  28 => 
  array (
    'id' => '29',
    'module_name' => 'block_manip',
    'module_version' => '1.70',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/block_manip.git',
    'private_clone_url' => 'git@github.com:diversen/block_manip.git',
  ),
);

$_PROFILE_TEMPLATES = array (
  0 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/clean.git',
    'private_clone_url' => 'git@github.com:diversen/clean.git',
    'module_version' => '1.70',
    'module_name' => 'clean',
  ),
  1 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/zimpleza.git',
    'private_clone_url' => 'git@github.com:diversen/zimpleza.git',
    'module_version' => '1.70',
    'module_name' => 'zimpleza',
  ),
  2 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/flowplayer.git',
    'private_clone_url' => 'git@github.com:diversen/flowplayer.git',
    'module_version' => '1.70',
    'module_name' => 'flowplayer',
  ),

  4 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/openid-selector.git',
    'private_clone_url' => 'git@github.com:diversen/openid-selector.git',
    'module_version' => '1.70',
    'module_name' => 'openid-selector',
  ),
  5 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/fancybox.git',
    'private_clone_url' => 'git@github.com:diversen/fancybox.git',
    'module_version' => '1.70',
    'module_name' => 'fancybox',
  ),
  6 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/js-toc.git',
    'private_clone_url' => 'git@github.com:diversen/js-toc.git',
    'module_version' => '1.70',
    'module_name' => 'js-toc',
  ),
  7 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/jquery-markedit.git',
    'private_clone_url' => 'git@github.com:diversen/jquery-markedit.git',
    'module_version' => '1.70',
    'module_name' => 'jquery-markedit',
  ),
);

$_PROFILE_TEMPLATE = 'zimpleza';

$_PROFILE_USE_HOME = 0;

