<?php 

$_PROFILE_MODULES = array (
  0 => 
  array (
    'id' => '1',
    'module_name' => 'system',
    'module_version' => '1.312',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/system.git',
    'private_clone_url' => 'git@github.com:diversen/system.git',
  ),
  1 => 
  array (
    'id' => '2',
    'module_name' => 'settings',
    'module_version' => '1.31',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/settings.git',
    'private_clone_url' => 'git@github.com:diversen/settings.git',
  ),
  2 => 
  array (
    'id' => '3',
    'module_name' => 'error',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/error.git',
    'private_clone_url' => 'git@github.com:diversen/error.git',
  ),
  3 => 
  array (
    'id' => '4',
    'module_name' => 'content',
    'module_version' => '1.311',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/content.git',
    'private_clone_url' => 'git@github.com:diversen/content.git',
  ),
  4 => 
  array (
    'id' => '5',
    'module_name' => 'files',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/files.git',
    'private_clone_url' => 'git@github.com:diversen/files.git',
  ),
  5 => 
  array (
    'id' => '6',
    'module_name' => 'account',
    'module_version' => '1.31',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account.git',
    'private_clone_url' => 'git@github.com:diversen/account.git',
  ),
  6 => 
  array (
    'id' => '7',
    'module_name' => 'google_analytics',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '5',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/google_analytics.git',
    'private_clone_url' => 'git@github.com:diversen/google_analytics.git',
  ),
  7 => 
  array (
    'id' => '8',
    'module_name' => 'account_profile',
    'module_version' => '1.311',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => 'account',
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account_profile.git',
    'private_clone_url' => 'git@github.com:diversen/account_profile.git',
  ),
  8 => 
  array (
    'id' => '10',
    'module_name' => 'gravatar',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/gravatar.git',
    'private_clone_url' => 'git@github.com:diversen/gravatar.git',
  ),
  9 => 
  array (
    'id' => '11',
    'module_name' => 'filter_php',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/filter_php.git',
    'private_clone_url' => 'git@github.com:diversen/filter_php.git',
  ),
  10 => 
  array (
    'id' => '12',
    'module_name' => 'filter_markdownExt',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/filter_markdownExt.git',
    'private_clone_url' => 'git@github.com:diversen/filter_markdownExt.git',
  ),
  11 => 
  array (
    'id' => '13',
    'module_name' => 'filter_markdown',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/filter_markdown.git',
    'private_clone_url' => 'git@github.com:diversen/filter_markdown.git',
  ),
  12 => 
  array (
    'id' => '14',
    'module_name' => 'comment',
    'module_version' => '1.31',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/comment.git',
    'private_clone_url' => 'git@github.com:diversen/comment.git',
  ),
  13 => 
  array (
    'id' => '15',
    'module_name' => 'tags',
    'module_version' => '1.31',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/tags.git',
    'private_clone_url' => 'git@github.com:diversen/tags.git',
  ),
  14 => 
  array (
    'id' => '16',
    'module_name' => 'blog',
    'module_version' => '1.311',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/blog.git',
    'private_clone_url' => 'git@github.com:diversen/blog.git',
  ),
  15 => 
  array (
    'id' => '17',
    'module_name' => 'remote',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => '1',
    'public_clone_url' => 'git://github.com/diversen/remote.git',
    'private_clone_url' => 'git@github.com:diversen/remote.git',
  ),
  16 => 
  array (
    'id' => '18',
    'module_name' => 'rss',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/rss.git',
    'private_clone_url' => 'git@github.com:diversen/rss.git',
  ),
  17 => 
  array (
    'id' => '19',
    'module_name' => 'addthis',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/addthis.git',
    'private_clone_url' => 'git@github.com:diversen/addthis.git',
  ),
  18 => 
  array (
    'id' => '20',
    'module_name' => 'reload_site',
    'module_version' => '1.31',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => '1',
    'public_clone_url' => 'git://github.com/diversen/reload_site.git',
    'private_clone_url' => 'git@github.com:diversen/reload_site.git',
  ),
  19 => 
  array (
    'id' => '21',
    'module_name' => 'configdb',
    'module_version' => '1.311',
    'menu_item' => '0',
    'run_level' => '2',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/configdb.git',
    'private_clone_url' => 'git@github.com:diversen/configdb.git',
  ),
);

$_PROFILE_TEMPLATES = array (
  0 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/clean.git',
    'private_clone_url' => 'git@github.com:diversen/clean.git',
    'module_version' => '1.31',
    'module_name' => 'clean',
  ),
  1 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/js-toc.git',
    'private_clone_url' => 'git@github.com:diversen/js-toc.git',
    'module_version' => '1.31',
    'module_name' => 'js-toc',
  ),
  2 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/1kbgrid.git',
    'private_clone_url' => 'git@github.com:diversen/1kbgrid.git',
    'module_version' => '1.31',
    'module_name' => '1kbgrid',
  ),
  3 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/jquery-markedit.git',
    'private_clone_url' => 'git@github.com:diversen/jquery-markedit.git',
    'module_version' => '1.31',
    'module_name' => 'jquery-markedit',
  ),
);

$_PROFILE_TEMPLATE = 'clean';

$_PROFILE_USE_HOME = 0;

