<?php

# basic language constructs in default modules
$_COS_LANG['home'] = 'Hjem';
$_COS_LANG['Edit'] = 'Rediger';
$_COS_LANG['Delete'] = 'Slet';
$_COS_LANG['Update'] = 'Opdater';
$_COS_LANG['Admin'] = 'Admin';
$_COS_LANG['Submit'] = 'Send';
$_COS_LANG['Search'] = 'Søg';
$_COS_LANG['View'] = 'Vis';
$_COS_LANG['Insert'] = 'Indsæt';
$_COS_LANG['Updated'] = 'Opdateret';

# weekdays
$_COS_LANG['Monday'] = 'Mandag';
$_COS_LANG['Tuesday'] = 'Tirsdag';
$_COS_LANG['Wednesday'] = 'Onsdag';
$_COS_LANG['Thursday'] = 'Torsdag';
$_COS_LANG['Friday'] = 'Fredag';
$_COS_LANG['Saturday'] = 'Lørdag';
$_COS_LANG['Sunday'] = 'Søndag';

$_COS_LANG['pager_prev_page'] = 'Forrige side';
$_COS_LANG['pager_next_page'] = 'Næste side';
$_COS_LANG['pager_page'] = 'Side';