<?php

// Translation of file /home/dennis/www/osnet/modules/video/delete.php

$_COS_LANG_MODULE['video_edit_file'] = 'Ret video';
// Translation of file /home/dennis/www/osnet/modules/video/add.php

$_COS_LANG_MODULE['video_add_file'] = 'Tilføj video';
// Translation of file /home/dennis/www/osnet/modules/video/model.video.inc

$_COS_LANG_MODULE['video_delete_file'] = 'Slet video';

$_COS_LANG_MODULE['video_edit_label'] = 'Ret video';
$_COS_LANG_MODULE['video_delete_label'] = 'Slet video';
$_COS_LANG_MODULE['video_add_label'] = 'Tilføj video';

$_COS_LANG_MODULE['video_edit'] = 'Ret';
$_COS_LANG_MODULE['video_delete'] = 'Slet';
$_COS_LANG_MODULE['video_add'] = 'Rediger videoer';

$_COS_LANG_MODULE['video_form_abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['video_form_file'] = 'Vælg video';
$_COS_LANG_MODULE['video_delete_caption'] = 'Slet video';
$_COS_LANG_MODULE['video_edit_caption'] = 'Ret video';
$_COS_LANG_MODULE['video_add_caption'] = 'Tilføj ny video';
$_COS_LANG_MODULE['video_no_file_specified'] = 'Ingen video valgt';
$_COS_LANG_MODULE['video_file_too_big'] = 'Fil er for stor';

$_COS_LANG_MODULE['video_attached'] = 'videoer';
$_COS_LANG_MODULE['video_download'] = 'Download';

$_COS_LANG_MODULE['video_add_new'] = 'Tilføj ny';
$_COS_LANG_MODULE['video_file_added'] = 'Fil tilføjet';
$_COS_LANG_MODULE['video_file_deleted'] = 'Fil slettet';
$_COS_LANG_MODULE['video_file_edited'] = 'Fil rettet';
// Translation of file /home/dennis/www/osnet/modules/video/edit.php


$_COS_LANG_MODULE['file_delete_label'] = 'Bekræft slet video';
$_COS_LANG_MODULE['file_edit_legend'] = 'Ret Fil';
$_COS_LANG_MODULE['file_add_legend'] = 'Tilføj Fil';
$_COS_LANG_MODULE['file_abstract_label'] = 'Abstrakt';
$_COS_LANG_MODULE['file_file_label'] = 'Vælg en video';
$_COS_LANG_MODULE['video_submit'] = 'Send';
