<?php

// Translation of file /home/dennis/www/osnet/modules/video/delete.php

$_COS_LANG_MODULE['video_edit_file'] = 'Edit video';
// Translation of file /home/dennis/www/osnet/modules/video/add.php

$_COS_LANG_MODULE['video_add_file'] = 'Edit video';
// Translation of file /home/dennis/www/osnet/modules/video/model.video.inc

$_COS_LANG_MODULE['video_delete_file'] = 'Delete video';

$_COS_LANG_MODULE['video_edit_label'] = 'Edit video';
$_COS_LANG_MODULE['video_delete_label'] = 'Delete video';
$_COS_LANG_MODULE['video_add_label'] = 'Add video';

$_COS_LANG_MODULE['video_edit'] = 'Edit';
$_COS_LANG_MODULE['video_delete'] = 'Delete';
$_COS_LANG_MODULE['video_add'] = 'Edit video';

$_COS_LANG_MODULE['video_form_abstract'] = 'Abstract';
$_COS_LANG_MODULE['video_form_file'] = 'Select video';
$_COS_LANG_MODULE['video_delete_caption'] = 'Delete video';
$_COS_LANG_MODULE['video_edit_caption'] = 'Edit video';
$_COS_LANG_MODULE['video_add_caption'] = 'Add new video';
$_COS_LANG_MODULE['video_no_file_specified'] = 'No video Specified';
$_COS_LANG_MODULE['video_file_too_big'] = 'File is to big';

$_COS_LANG_MODULE['video_attached'] = 'Video';
$_COS_LANG_MODULE['video_download'] = 'Download';

$_COS_LANG_MODULE['video_add_new'] = 'Add New';
$_COS_LANG_MODULE['video_file_added'] = 'Video added';
$_COS_LANG_MODULE['video_file_deleted'] = 'Video deleted';
$_COS_LANG_MODULE['video_file_edited'] = 'Video edited';
// Translation of file /home/dennis/www/osnet/modules/video/edit.php


$_COS_LANG_MODULE['file_delete_label'] = 'Delete video';
$_COS_LANG_MODULE['system_submit_delete'] = 'Delete';
$_COS_LANG_MODULE['file_edit_legend'] = 'Edit video';
$_COS_LANG_MODULE['file_add_legend'] = 'Add video';
$_COS_LANG_MODULE['file_abstract_label'] = 'Abstract';
$_COS_LANG_MODULE['file_file_label'] = 'video';

$_COS_LANG_MODULE['video_could_not_transform_to_flv'] = 'Failed transforming video to compress video to flv';
