<?php

# basic language constructs in default modules
$_COS_LANG['home'] = 'Home';
$_COS_LANG['Edit'] = 'Edit';
$_COS_LANG['Delete'] = 'Delete';
$_COS_LANG['Update'] = 'Update';
$_COS_LANG['Admin'] = 'Admin';
$_COS_LANG['Submit'] = 'Submit';
$_COS_LANG['Search'] = 'Search';
$_COS_LANG['View'] = 'View';
$_COS_LANG['Insert'] = 'Insert';
$_COS_LANG['Updated'] = 'Updated';

# weekdays
$_COS_LANG['Monday'] = 'Monday';
$_COS_LANG['Tuesday'] = 'Tuesday';
$_COS_LANG['Wednesday'] = 'Wednesday';
$_COS_LANG['Thursday'] = 'Thursday';
$_COS_LANG['Friday'] = 'Friday';
$_COS_LANG['Saturday'] = 'Saturday';
$_COS_LANG['Sunday'] = 'Sunday';

$_COS_LANG['pager_prev_page'] = 'Previous Page';
$_COS_LANG['pager_next_page'] = 'Next Page';
$_COS_LANG['pager_page'] = 'Page';