<?php

// Translation of file /home/dennis/www/osnet/modules/video/delete.php

$_COS_LANG_MODULE['video_edit_file'] = 'Edit File';
// Translation of file /home/dennis/www/osnet/modules/video/add.php

$_COS_LANG_MODULE['video_add_file'] = 'Add File';
// Translation of file /home/dennis/www/osnet/modules/video/model.video.inc

$_COS_LANG_MODULE['video_delete_file'] = 'Delete File';

$_COS_LANG_MODULE['video_edit_label'] = 'Edit File';
$_COS_LANG_MODULE['video_delete_label'] = 'Delete File';
$_COS_LANG_MODULE['video_add_label'] = 'Add File';

$_COS_LANG_MODULE['video_edit'] = 'Edit';
$_COS_LANG_MODULE['video_delete'] = 'Delete';
$_COS_LANG_MODULE['video_add'] = 'Add New File';

$_COS_LANG_MODULE['video_form_abstract'] = 'Abstract';
$_COS_LANG_MODULE['video_form_file'] = 'Select File';
$_COS_LANG_MODULE['video_delete_caption'] = 'Delete File';
$_COS_LANG_MODULE['video_edit_caption'] = 'Edit File';
$_COS_LANG_MODULE['video_add_caption'] = 'Add New File';
$_COS_LANG_MODULE['video_no_file_specified'] = 'No File Specified';
$_COS_LANG_MODULE['video_file_too_big'] = 'file is to big';

$_COS_LANG_MODULE['video_attached'] = 'video';
$_COS_LANG_MODULE['video_download'] = 'Download';

$_COS_LANG_MODULE['video_add_new'] = 'Add New';
$_COS_LANG_MODULE['video_file_added'] = 'File Added';
$_COS_LANG_MODULE['video_file_deleted'] = 'File Deleted';
$_COS_LANG_MODULE['video_file_edited'] = 'File Edited';
// Translation of file /home/dennis/www/osnet/modules/video/edit.php


$_COS_LANG_MODULE['file_delete_label'] = 'Delete File';
$_COS_LANG_MODULE['system_submit_delete'] = 'Delete';
$_COS_LANG_MODULE['file_edit_legend'] = 'Edit File';
$_COS_LANG_MODULE['file_add_legend'] = 'Add File';
$_COS_LANG_MODULE['file_abstract_label'] = 'Abstract';
$_COS_LANG_MODULE['file_file_label'] = 'File';
