#!/usr/bin/env php
<?php

include_once "vendor/autoload.php";
use diversen\conf;
use diversen\autoloader\modules;

$path = dirname(__FILE__);
conf::setMainIni('base_path', $path); 
conf::defineCommon();
conf::setIncludePath();

$m = new modules();
$m->autoloadRegister();

use modules\remote\commands\remote;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new remote());
$application->run();
//exit($ret);
