<?php

/**
 * @package shell
 */

/*
mainCli::setCommand('base', array(
    'description' => 'Commands for upgrading base system',
));

// create commandline parser
mainCli::setOption('list_tags', array(
    'long_name'   => '--tags',
    'description' => 'Will list git tags of base system',
    'action'      => 'StoreTrue'
));

mainCli::setOption( 'force_confirm_readline', array(
    'long_name'   => '--force',
    'short_name'   => '-f',
    'description' => 'will force execution. No questions asked',
    'action'      => 'StoreTrue'
));

mainCli::setArgument(
    'Version',
    array('description'=> 'Specify the version to upgrade or downgrade to',
        'optional' => true,
));

*/