<?php 

$_PROFILE_MODULES = array (
  0 => 
  array (
    'id' => '1',
    'module_name' => 'error',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/error.git',
  ),
  1 => 
  array (
    'id' => '2',
    'module_name' => 'settings',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/settings.git',
  ),
  2 => 
  array (
    'id' => '6',
    'module_name' => 'content',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/content.git',
  ),
  3 => 
  array (
    'id' => '41',
    'module_name' => 'comment',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/comment.git',
  ),
  4 => 
  array (
    'id' => '49',
    'module_name' => 'files',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/files.git',
  ),
  5 => 
  array (
    'id' => '146',
    'module_name' => 'account',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account.git',
  ),
  6 => 
  array (
    'id' => '166',
    'module_name' => 'google_analytics',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '5',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/google_analytics.git',
  ),
  7 => 
  array (
    'id' => '182',
    'module_name' => 'system',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/system.git',
  ),
  8 => 
  array (
    'id' => '207',
    'module_name' => 'account_profile',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => 'account',
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account_profile.git',
  ),
  9 => 
  array (
    'id' => '210',
    'module_name' => 'module_system_git',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/module_system_git.git',
  ),
  10 => 
  array (
    'id' => '219',
    'module_name' => 'filter_markdown',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/filter_markdown.git',
  ),
  11 => 
  array (
    'id' => '220',
    'module_name' => 'filter_language',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/filter_language.git',
  ),
  12 => 
  array (
    'id' => '221',
    'module_name' => 'gravatar',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/gravatar.git',
  ),
  13 => 
  array (
    'id' => '222',
    'module_name' => 'filter_safe',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/filter_safe.git',
  ),
);

$_PROFILE_TEMPLATES = array (
  0 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/highlight.git',
    'module_version' => 'master',
    'module_name' => 'highlight',
  ),
  1 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/clean.git',
    'module_version' => 'master',
    'module_name' => 'clean',
  ),
  2 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/fancybox.git',
    'module_version' => 'master',
    'module_name' => 'fancybox',
  ),
);

$_PROFILE_TEMPLATE = 'clean';

$_PROFILE_USE_HOME = 0;

