<?php 

$_PROFILE_MODULES = array (
  0 => 
  array (
    'id' => '2',
    'module_name' => 'settings',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/settings.git',
  ),
  1 => 
  array (
    'id' => '3',
    'module_name' => 'files',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/files.git',
  ),
  2 => 
  array (
    'id' => '8',
    'module_name' => 'image',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/image.git',
  ),
  3 => 
  array (
    'id' => '9',
    'module_name' => 'order',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/order.git',
  ),
  4 => 
  array (
    'id' => '10',
    'module_name' => 'content',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/content.git',
  ),
  5 => 
  array (
    'id' => '11',
    'module_name' => 'account',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account.git',
  ),
  6 => 
  array (
    'id' => '13',
    'module_name' => 'newsletter',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/newsletter.git',
  ),
  7 => 
  array (
    'id' => '14',
    'module_name' => 'recommend',
    'module_version' => 'master',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/recommend.git',
  ),
  8 => 
  array (
    'id' => '15',
    'module_name' => 'system',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/system.git',
  ),
  9 => 
  array (
    'id' => '16',
    'module_name' => 'mail_form',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/mail_form.git',
  ),
  10 => 
  array (
    'id' => '17',
    'module_name' => 'system_backup',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => 'system',
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/system_backup.git',
  ),
  11 => 
  array (
    'id' => '18',
    'module_name' => 'comment',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/comment.git',
  ),
  12 => 
  array (
    'id' => '19',
    'module_name' => 'error',
    'module_version' => 'master',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/error.git',
  ),
);

$_PROFILE_TEMPLATES = array (
  0 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/mandlen.git',
    'module_version' => 'master',
    'module_name' => 'mandlen',
  ),
);

$_PROFILE_TEMPLATE = 'mandlen';

$_PROFILE_USE_HOME = 0;

