<?php 

$_PROFILE_MODULES = array (
  0 => 
  array (
    'id' => '1',
    'module_name' => 'error',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/error.git',
  ),
  1 => 
  array (
    'id' => '2',
    'module_name' => 'settings',
    'module_version' => '1.037',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/settings.git',
  ),
  2 => 
  array (
    'id' => '3',
    'module_name' => 'account',
    'module_version' => '1.023',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account.git',
  ),
  3 => 
  array (
    'id' => '5',
    'module_name' => 'gallery',
    'module_version' => '1.01',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/gallery.git',
  ),
  4 => 
  array (
    'id' => '6',
    'module_name' => 'event',
    'module_version' => '1.09',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/event.git',
  ),
  5 => 
  array (
    'id' => '10',
    'module_name' => 'comment',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/comment.git',
  ),
  6 => 
  array (
    'id' => '11',
    'module_name' => 'content',
    'module_version' => '1.1',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/content.git',
  ),
  7 => 
  array (
    'id' => '14',
    'module_name' => 'google_contact',
    'module_version' => '1.01',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/google_contact.git',
  ),
  8 => 
  array (
    'id' => '16',
    'module_name' => 'files',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/files.git',
  ),
  9 => 
  array (
    'id' => '20',
    'module_name' => 'image',
    'module_version' => '1.011',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/image.git',
  ),
  10 => 
  array (
    'id' => '21',
    'module_name' => 'system',
    'module_version' => '1.016',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'public_clone_url' => 'git://github.com/diversen/system.git',
  ),
);

$_PROFILE_TEMPLATE = 'bartels';

$_PROFILE_USE_HOME = 0;

