<?php 

$_PROFILE_MODULES = array (
  0 => 
  array (
    'id' => '1',
    'module_name' => 'error',
    'module_version' => '1.011',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/error.git',
  ),
  1 => 
  array (
    'id' => '2',
    'module_name' => 'settings',
    'module_version' => '1.037',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/settings.git',
  ),
  2 => 
  array (
    'id' => '4',
    'module_name' => 'content',
    'module_version' => '1.11',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/content.git',
  ),
  3 => 
  array (
    'id' => '10',
    'module_name' => 'files',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/files.git',
  ),
  4 => 
  array (
    'id' => '44',
    'module_name' => 'rewrite',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/rewrite.git',
  ),
  5 => 
  array (
    'id' => '45',
    'module_name' => 'rewrite_manip',
    'module_version' => '1.07',
    'menu_item' => '0',
    'run_level' => '0,1',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/rewrite_manip.git',
  ),
  6 => 
  array (
    'id' => '46',
    'module_name' => 'account',
    'module_version' => '1.023',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account.git',
  ),
  7 => 
  array (
    'id' => '47',
    'module_name' => 'google_analytics',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '5',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/google_analytics.git',
  ),
  8 => 
  array (
    'id' => '49',
    'module_name' => 'gallery',
    'module_version' => '1.01',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/gallery.git',
  ),
  9 => 
  array (
    'id' => '65',
    'module_name' => 'system',
    'module_version' => '1.016',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/system.git',
  ),
  10 => 
  array (
    'id' => '69',
    'module_name' => 'comment',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/comment.git',
  ),
  11 => 
  array (
    'id' => '85',
    'module_name' => 'account_profile',
    'module_version' => '1.001',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => 'account',
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/account_profile.git',
  ),
  12 => 
  array (
    'id' => '89',
    'module_name' => 'blog_simple',
    'module_version' => '1.01',
    'menu_item' => '1',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/blog_simple.git',
  ),
  13 => 
  array (
    'id' => '90',
    'module_name' => 'filter_youtube',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/filter_youtube.git',
  ),
  14 => 
  array (
    'id' => '92',
    'module_name' => 'filter_language',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => NULL,
  ),
  15 => 
  array (
    'id' => '93',
    'module_name' => 'gravatar',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/gravatar.git',
  ),
  16 => 
  array (
    'id' => '94',
    'module_name' => 'image',
    'module_version' => '1.011',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/image.git',
  ),
  17 => 
  array (
    'id' => '96',
    'module_name' => 'filter_markdownExt',
    'module_version' => '1.01',
    'menu_item' => '0',
    'run_level' => '0',
    'load_on' => NULL,
    'parent' => NULL,
    'is_shell' => NULL,
    'public_clone_url' => 'git://github.com/diversen/filter_markdownExt.git',
  ),
);

$_PROFILE_TEMPLATES = array (
  0 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/js-toc.git',
    'module_version' => '1.03',
    'module_name' => 'js-toc',
  ),
  1 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/zimpleza.git',
    'module_version' => '1.03',
    'module_name' => 'zimpleza',
  ),
  2 => 
  array (
    'public_clone_url' => 'git://github.com/diversen/fancybox.git',
    'module_version' => '1.03',
    'module_name' => 'fancybox',
  ),
);

$_PROFILE_TEMPLATE = 'zimpleza';

$_PROFILE_USE_HOME = 0;

